#!/bin/bash

cd $(dirname $0) 

docker ps | grep flask

if [ $? -eq 0 ] ; then
docker stop flask
docker rm flask
fi

docker ps -a | grep flask

if [ $? -eq 0 ] ; then
docker rm flask
fi

docker build -t flask .
docker run --name flask -p 5000:5000 -d -e LINE_ACCESS_TOKEN -e LINE_CHANNEL_SECRET -v /certs/flask/:/certs/ flask
